/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as FirmwareRouteImport } from './routes/firmware'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevicesDeviceIdRouteImport } from './routes/devices/$deviceId'
import { Route as DevicesDeviceIdWebhooksRouteImport } from './routes/devices/$deviceId.webhooks'
import { Route as DevicesDeviceIdSettingsRouteImport } from './routes/devices/$deviceId.settings'
import { Route as DevicesDeviceIdScriptsRouteImport } from './routes/devices/$deviceId.scripts'
import { Route as DevicesDeviceIdKvsRouteImport } from './routes/devices/$deviceId.kvs'
import { Route as DevicesDeviceIdConfigRouteImport } from './routes/devices/$deviceId.config'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmwareRoute = FirmwareRouteImport.update({
  id: '/firmware',
  path: '/firmware',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesDeviceIdRoute = DevicesDeviceIdRouteImport.update({
  id: '/devices/$deviceId',
  path: '/devices/$deviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesDeviceIdWebhooksRoute = DevicesDeviceIdWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => DevicesDeviceIdRoute,
} as any)
const DevicesDeviceIdSettingsRoute = DevicesDeviceIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DevicesDeviceIdRoute,
} as any)
const DevicesDeviceIdScriptsRoute = DevicesDeviceIdScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => DevicesDeviceIdRoute,
} as any)
const DevicesDeviceIdKvsRoute = DevicesDeviceIdKvsRouteImport.update({
  id: '/kvs',
  path: '/kvs',
  getParentRoute: () => DevicesDeviceIdRoute,
} as any)
const DevicesDeviceIdConfigRoute = DevicesDeviceIdConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => DevicesDeviceIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/firmware': typeof FirmwareRoute
  '/settings': typeof SettingsRoute
  '/devices/$deviceId': typeof DevicesDeviceIdRouteWithChildren
  '/devices/$deviceId/config': typeof DevicesDeviceIdConfigRoute
  '/devices/$deviceId/kvs': typeof DevicesDeviceIdKvsRoute
  '/devices/$deviceId/scripts': typeof DevicesDeviceIdScriptsRoute
  '/devices/$deviceId/settings': typeof DevicesDeviceIdSettingsRoute
  '/devices/$deviceId/webhooks': typeof DevicesDeviceIdWebhooksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/firmware': typeof FirmwareRoute
  '/settings': typeof SettingsRoute
  '/devices/$deviceId': typeof DevicesDeviceIdRouteWithChildren
  '/devices/$deviceId/config': typeof DevicesDeviceIdConfigRoute
  '/devices/$deviceId/kvs': typeof DevicesDeviceIdKvsRoute
  '/devices/$deviceId/scripts': typeof DevicesDeviceIdScriptsRoute
  '/devices/$deviceId/settings': typeof DevicesDeviceIdSettingsRoute
  '/devices/$deviceId/webhooks': typeof DevicesDeviceIdWebhooksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/firmware': typeof FirmwareRoute
  '/settings': typeof SettingsRoute
  '/devices/$deviceId': typeof DevicesDeviceIdRouteWithChildren
  '/devices/$deviceId/config': typeof DevicesDeviceIdConfigRoute
  '/devices/$deviceId/kvs': typeof DevicesDeviceIdKvsRoute
  '/devices/$deviceId/scripts': typeof DevicesDeviceIdScriptsRoute
  '/devices/$deviceId/settings': typeof DevicesDeviceIdSettingsRoute
  '/devices/$deviceId/webhooks': typeof DevicesDeviceIdWebhooksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/firmware'
    | '/settings'
    | '/devices/$deviceId'
    | '/devices/$deviceId/config'
    | '/devices/$deviceId/kvs'
    | '/devices/$deviceId/scripts'
    | '/devices/$deviceId/settings'
    | '/devices/$deviceId/webhooks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/firmware'
    | '/settings'
    | '/devices/$deviceId'
    | '/devices/$deviceId/config'
    | '/devices/$deviceId/kvs'
    | '/devices/$deviceId/scripts'
    | '/devices/$deviceId/settings'
    | '/devices/$deviceId/webhooks'
  id:
    | '__root__'
    | '/'
    | '/discover'
    | '/firmware'
    | '/settings'
    | '/devices/$deviceId'
    | '/devices/$deviceId/config'
    | '/devices/$deviceId/kvs'
    | '/devices/$deviceId/scripts'
    | '/devices/$deviceId/settings'
    | '/devices/$deviceId/webhooks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoverRoute: typeof DiscoverRoute
  FirmwareRoute: typeof FirmwareRoute
  SettingsRoute: typeof SettingsRoute
  DevicesDeviceIdRoute: typeof DevicesDeviceIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firmware': {
      id: '/firmware'
      path: '/firmware'
      fullPath: '/firmware'
      preLoaderRoute: typeof FirmwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices/$deviceId': {
      id: '/devices/$deviceId'
      path: '/devices/$deviceId'
      fullPath: '/devices/$deviceId'
      preLoaderRoute: typeof DevicesDeviceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices/$deviceId/webhooks': {
      id: '/devices/$deviceId/webhooks'
      path: '/webhooks'
      fullPath: '/devices/$deviceId/webhooks'
      preLoaderRoute: typeof DevicesDeviceIdWebhooksRouteImport
      parentRoute: typeof DevicesDeviceIdRoute
    }
    '/devices/$deviceId/settings': {
      id: '/devices/$deviceId/settings'
      path: '/settings'
      fullPath: '/devices/$deviceId/settings'
      preLoaderRoute: typeof DevicesDeviceIdSettingsRouteImport
      parentRoute: typeof DevicesDeviceIdRoute
    }
    '/devices/$deviceId/scripts': {
      id: '/devices/$deviceId/scripts'
      path: '/scripts'
      fullPath: '/devices/$deviceId/scripts'
      preLoaderRoute: typeof DevicesDeviceIdScriptsRouteImport
      parentRoute: typeof DevicesDeviceIdRoute
    }
    '/devices/$deviceId/kvs': {
      id: '/devices/$deviceId/kvs'
      path: '/kvs'
      fullPath: '/devices/$deviceId/kvs'
      preLoaderRoute: typeof DevicesDeviceIdKvsRouteImport
      parentRoute: typeof DevicesDeviceIdRoute
    }
    '/devices/$deviceId/config': {
      id: '/devices/$deviceId/config'
      path: '/config'
      fullPath: '/devices/$deviceId/config'
      preLoaderRoute: typeof DevicesDeviceIdConfigRouteImport
      parentRoute: typeof DevicesDeviceIdRoute
    }
  }
}

interface DevicesDeviceIdRouteChildren {
  DevicesDeviceIdConfigRoute: typeof DevicesDeviceIdConfigRoute
  DevicesDeviceIdKvsRoute: typeof DevicesDeviceIdKvsRoute
  DevicesDeviceIdScriptsRoute: typeof DevicesDeviceIdScriptsRoute
  DevicesDeviceIdSettingsRoute: typeof DevicesDeviceIdSettingsRoute
  DevicesDeviceIdWebhooksRoute: typeof DevicesDeviceIdWebhooksRoute
}

const DevicesDeviceIdRouteChildren: DevicesDeviceIdRouteChildren = {
  DevicesDeviceIdConfigRoute: DevicesDeviceIdConfigRoute,
  DevicesDeviceIdKvsRoute: DevicesDeviceIdKvsRoute,
  DevicesDeviceIdScriptsRoute: DevicesDeviceIdScriptsRoute,
  DevicesDeviceIdSettingsRoute: DevicesDeviceIdSettingsRoute,
  DevicesDeviceIdWebhooksRoute: DevicesDeviceIdWebhooksRoute,
}

const DevicesDeviceIdRouteWithChildren = DevicesDeviceIdRoute._addFileChildren(
  DevicesDeviceIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoverRoute: DiscoverRoute,
  FirmwareRoute: FirmwareRoute,
  SettingsRoute: SettingsRoute,
  DevicesDeviceIdRoute: DevicesDeviceIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
