/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as FirmwareRouteImport } from './routes/firmware'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevicesDeviceIdRouteImport } from './routes/devices/$deviceId'
import { Route as DevicesDeviceIdSettingsRouteImport } from './routes/devices/$deviceId.settings'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmwareRoute = FirmwareRouteImport.update({
  id: '/firmware',
  path: '/firmware',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesDeviceIdRoute = DevicesDeviceIdRouteImport.update({
  id: '/devices/$deviceId',
  path: '/devices/$deviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesDeviceIdSettingsRoute = DevicesDeviceIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DevicesDeviceIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/firmware': typeof FirmwareRoute
  '/settings': typeof SettingsRoute
  '/devices/$deviceId': typeof DevicesDeviceIdRouteWithChildren
  '/devices/$deviceId/settings': typeof DevicesDeviceIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/firmware': typeof FirmwareRoute
  '/settings': typeof SettingsRoute
  '/devices/$deviceId': typeof DevicesDeviceIdRouteWithChildren
  '/devices/$deviceId/settings': typeof DevicesDeviceIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/firmware': typeof FirmwareRoute
  '/settings': typeof SettingsRoute
  '/devices/$deviceId': typeof DevicesDeviceIdRouteWithChildren
  '/devices/$deviceId/settings': typeof DevicesDeviceIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/firmware'
    | '/settings'
    | '/devices/$deviceId'
    | '/devices/$deviceId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/firmware'
    | '/settings'
    | '/devices/$deviceId'
    | '/devices/$deviceId/settings'
  id:
    | '__root__'
    | '/'
    | '/discover'
    | '/firmware'
    | '/settings'
    | '/devices/$deviceId'
    | '/devices/$deviceId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoverRoute: typeof DiscoverRoute
  FirmwareRoute: typeof FirmwareRoute
  SettingsRoute: typeof SettingsRoute
  DevicesDeviceIdRoute: typeof DevicesDeviceIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firmware': {
      id: '/firmware'
      path: '/firmware'
      fullPath: '/firmware'
      preLoaderRoute: typeof FirmwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices/$deviceId': {
      id: '/devices/$deviceId'
      path: '/devices/$deviceId'
      fullPath: '/devices/$deviceId'
      preLoaderRoute: typeof DevicesDeviceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices/$deviceId/settings': {
      id: '/devices/$deviceId/settings'
      path: '/settings'
      fullPath: '/devices/$deviceId/settings'
      preLoaderRoute: typeof DevicesDeviceIdSettingsRouteImport
      parentRoute: typeof DevicesDeviceIdRoute
    }
  }
}

interface DevicesDeviceIdRouteChildren {
  DevicesDeviceIdSettingsRoute: typeof DevicesDeviceIdSettingsRoute
}

const DevicesDeviceIdRouteChildren: DevicesDeviceIdRouteChildren = {
  DevicesDeviceIdSettingsRoute: DevicesDeviceIdSettingsRoute,
}

const DevicesDeviceIdRouteWithChildren = DevicesDeviceIdRoute._addFileChildren(
  DevicesDeviceIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoverRoute: DiscoverRoute,
  FirmwareRoute: FirmwareRoute,
  SettingsRoute: SettingsRoute,
  DevicesDeviceIdRoute: DevicesDeviceIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
